### ISSUE TITLE
Azure authentication by tenant, appId, secret

### ISSUE THREAD

**Issue by robertZaufall** [KenSpur/terraform-provider-azure-iot-central#1]
Would be nice, if you could enhance the provider settings to use also tenant, appId and secret to get a valid access token.

Problem is, I'm using this kind of authentication when provisioning IoTCentral and all other Azure resources (using azurerm, azapi) but then only the Service Principle User has sufficient rights to access IoTCentral.  

In c# this looks like this:  

```csharp
credential = new ClientSecretCredential(tenantId, appId, secret);

var rolesClient = new RolesClient(subdomain, credential);
var roles = rolesClient?.List()?.ToList();
var orgAdmin = roles.First(x => x.DisplayName.Contains("Admin"));

var usersClient = new UsersClient(subdomain, credential);
var users = usersClient?.List()?.ToList();
if (users != null && !users.Any(x => x.Id == id))
{
    _ = usersClient.Create(id, new EmailUser(new RoleAssignment[] { new RoleAssignment(orgAdmin.Id) }, email)).Value;
}

var orgsClient = new OrganizationsClient(subdomain, credential);
...
```

Keep up your awesome work! 👍😃

**Comment by KenSpur** [comment]
Hey @robertZaufall,

Thanks for the input! I understand the flexibility of being able to use tenant, appId, and secret for authentication. I'll definitely take a closer look on Wednesday to see if I can expand the authentication methods similar to what the azurerm/azapi providers offer.

Just to mention, the current implementation uses `DefaultAzureCredential`, which can authenticate using the Azure CLI:

```shell
az login --service-principal --username <client-id> --password <client-secret> --tenant <tenant-id>
```

Here, `client-id` and `client-secret` correspond to `appId` and `secret` in your C# example.

Stay tuned, and thanks for your support! 👍

**Comment by KenSpur** [comment]
@robertZaufall 

I've decided to chase the implementation of the iotcentral data plane in the [hashicorp/go-azure-sdk](https://github.com/hashicorp/go-azure-sdk) at [#527](https://github.com/hashicorp/go-azure-sdk/issues/527).

So that i can then start the implementation of the data plane resources in the [terraform-provider-azurerm](https://github.com/hashicorp/terraform-provider-azurerm).

I did not intend to fully build this provider out myself, its my first attempt at a provider and a great mvp in order to learn terraform provider development. ref: [tutorials/providers-plugin-framework](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework).

If you do want to build in a quickfix for your usecases, feel free to create a pull request. [tutorials/providers-plugin-framework](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework) should set you of to get familiar with provider development.

**Comment by robertZaufall** [comment]
@KenSpur 

Thanks for the information.
At the moment I'm using a console application written in c# as a workaround.

Feel free to close the issue.
